{% set version = "4.31" %}

package:
  name: nspr
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/nspr/releases/v{{ version }}/src/nspr-{{ version }}.tar.gz
  sha256: 5729da87d5fbf1584b72840751e0c6f329b5d541850cacd1b61652c95015abc8

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('nspr', max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - sed
  # https://github.com/Quansight/omnisci/issues/20#issuecomment-422294770
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx]

test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}         # [unix]
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}          # [unix]
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}         # [unix]
    - test -d ${PREFIX}/include/nspr                     # [unix]
    - test -f ${PREFIX}/bin/nspr-config                  # [unix]

about:
  home: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  license: MPL-2.0
  license_file: nspr/LICENSE
  summary: A platform-neutral API for system level and libc-like functions.
  description: |
    NetScape Portable Runtime (NSPR) provides platform independence for
    non-GUI operating system facilities. These facilities include threads,
    thread synchronization, normal file and network I/O, interval timing and
    calendar time, basic memory management (malloc and free) and shared
    library linking.
  doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
  dev_url: https://developer.mozilla.org/en-US/docs/MDN

extra:
  recipe-maintainers:
    - marcelotrevisani
    - jakirkham
