# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HYibEhI4t76Xl6qQeNVE+O5s/XCNS2JjmyxzvkrHA037BSY5L+0NLjKqUiol2NheYjXaIQx2/xVCAi90/hp6CquI+M5hTb5eWndgjx26XHnzWTrInbOQ/qSEwlHvqMHdh+QG/R6/TcfXo739DfMgjnAPlsQyudKSgfp46P7bO4z4/wQ+USWxSp5KwHANAEAwsysVRR74+C7W8apB/tkPNPq093fCaXkW1ZFBRWglGrH5TRvnLnA4MXi9pCgbUmeHZUJRJTmU1MOQEZD3g+isro/OO2+4I45EHFQdD3yU/wdS1RtQCmQeWevxzlWvSCI4TN/rJpu/dE+Yq/nJ54vCSeBqM85mPvMXMkdRBzRq+JxtNMcZS5fQYLIOYRENUallFynejQLB++eRely8CLzgA4ySZxj/TyvsdfpIlyF5kRiJraZjfMLj53T4nJr90MrLeqZlsjFwTnZS4MD9Q9l9uDOs0lg4eJssamsdL8MIvwjWHo1j4c6YO7iVe8fzce0mH38v85GntB02ftOdbCz6OiqesQswuxbsEAuUb8uC8deqE2N960DM1BRPKDFzcMYcZrfio6E+14l4XG5uOof0hLJoWlwkjdPpOvrHDu9xnFdfFPikXPwvQWH7zwoHiK6LUStAeR2C6vQjEUQL+Sh5CMQEkPo+9Cq+YiV1ZA9hFkk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
